apiVersion: apps/v1
kind: Deployment
metadata:
  name: coit-backend1
  labels:
    app: coit-backend1
spec:
  selector:
    matchLabels:
      app: coit-backend1
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: coit-backend1
    spec:
      containers:
      - image: radhaneelam/coit-backend1:v1.0
        imagePullPolicy: IfNotPresent
        name: coit-backend1
        env:
          - name: SA_LOGIC_API_URL
            valueFrom:
              configMapKeyRef:
                name: coit-backend1-config
                key: python_url
        ports:
          - containerPort: 8080
