apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./coit-backend1-deployment.yaml
- ./coit-backend1-service.yaml


configMapGenerator:
- name: coit-backend1-config
  envs:
  - application.properties

commonLabels:
  app: coit-backend1
  managed-by: kustomize

